---
- name: Deploy Flask app from GitHub
  hosts: servers
  become: yes
  vars:
    repo_url: https://github.com/Daswwy/flask-postgres-docker.git
    project_dir: /opt/flask-app

  tasks:
    - name: Install git and docker compose plugin
      apt:
        name:
          - git
          - docker-compose-plugin
        state: present
        update_cache: yes

    - name: Clone or update the repo
      git:
        repo: "{{ repo_url }}"
        dest: "{{ project_dir }}"
        version: main

    - name: Create .env with database credentials
      copy:
        dest: "{{ project_dir }}/.env"
        content: |
          POSTGRES_USER= {{ postgres_user }}
          POSTGRES_DB= {{ postgres_db }}
          POSTGRES_PASSWORD= {{ postgres_password }}
        mode: "0600"
      no_log: true

    - name: Create htpasswd for /metrics
      copy:
        dest: "{{ project_dir }}/nginx/.htpasswd"
        content: "prometheus:{{ vault_metrics_password | password_hash('sha512', 'flaskmetrics') }}\n"
        mode: "0644"
      no_log: true


    - name: Build and start containers
      command: docker compose up -d --build
      args:
        chdir: "{{ project_dir }}"
